ALTER TABLE "property_details" ADD COLUMN "property_id" varchar;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "decade_built" integer;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "building_construction" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "building_condition" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "floor_area" integer;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "land_area" integer;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "has_deck" boolean;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "view_type" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "view_scope" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "zone" jsonb;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "trees" jsonb;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "contour" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "mass_total_living_area" jsonb;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "legal_description" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "category_code" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "certificate_of_title" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "valuation_reference_number" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "land_use" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "estimated_lower_value" integer;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "estimated_upper_value" integer;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "estimated_value" integer;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "estimated_rental_lower_value" integer;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "estimated_rental_upper_value" integer;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "bath_estimate" integer;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "bath_estimate_date" timestamp;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "bed_estimate" integer;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "bed_estimate_date" timestamp;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "suburb_name" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "city_name" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "claim_id" jsonb;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "claimed" boolean;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "user_events" jsonb;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "display_estimated_lower_value" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "display_estimated_upper_value" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "display_estimated_value" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "display_estimated_rental_lower_value" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "display_estimated_rental_upper_value" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "building_site_coverage" jsonb;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "mass_garage_freestanding" jsonb;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "mass_garage_under_roof" jsonb;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "solar" jsonb;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "capital_value_digit" integer;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "improvement_value_digit" integer;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "land_value_digit" integer;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "display_capital_value" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "display_improvement_value" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "display_land_value" text;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "image_urls" jsonb;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "images" jsonb;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "video_urls" jsonb;--> statement-breakpoint
ALTER TABLE "property_details" ADD COLUMN "core_logic_id" integer;