CREATE TABLE "listings" (
	"id" text PRIMARY KEY NOT NULL,
	"date_scraped" timestamp,
	"item_id" text,
	"property_id" varchar,
	"listing_id" text,
	"tm_ids" text[],
	"branch_id" varchar,
	"branch_ids" text[],
	"state" integer,
	"sales_count" integer,
	"property_detail_id" varchar,
	"point" jsonb,
	"display_price" text,
	"price" text,
	"date" timestamp,
	"featured_at" timestamp,
	"featured_plan" integer,
	"agent_id" varchar,
	"agent_ids" text[],
	"url" text,
	"display_price_short" text,
	"property_estimate_history" jsonb,
	"property_sales_valuation_history" jsonb
);
